@url = http://localhost:3000/projects

### Get all projects
GET {{url}}/

### Get one project
GET {{url}}/6566642b2633149d570c8976

### Post a project
POST {{url}}/
Content-Type: application/json

{
  "name": "Videogames",
  "title": "Videogames",
  "image": "https://res.cloudinary.com/santiagosdeb/image/upload/v1700522137/Portfolio/Projects/al05gqcp6f57kl9wxidp.png",
  "skills": ["HTML", "CSS", "Javascript", "ReactJS", "Tailwind", "Responsive Web Design"],
  "description": "Descripcion",
  "links": [ {"CODE": "https://github.com/santiagosdeb/videogames", "VIDEO": "no hay aun", "DEPLOY": "no deploy" } ]
}

### Update a project
PUT {{url}}/6566642b2633149d570c8976
Content-Type: application/json

{
  "image": "https://res.cloudinary.com/santiagosdeb/image/upload/v1700522136/Portfolio/Projects/lwrlnn05vwzzxcdruhue.jpg"
}

### Delete a project
GET {{url}}/delete/653c24283551c38a8fb985ac